---
all:
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: '~/.vagrant.d/insecure_private_key'
  children:
    docker_swarm_manager:
      hosts:
        box1:
    docker_swarm_worker:
      hosts:
        box2:
        box3: